package main

const dashboardHTML = `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>UMA Slave Control</title>
<style>
:root{color-scheme:dark;--bg:#071019;--panel:#0d1925;--line:#203548;--text:#e8f1f7;--muted:#8ba1b1;--cyan:#39d8d0;--green:#43dc8b;--amber:#ffbf5a;--red:#ff657a}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 10% 0,#14334a 0,var(--bg) 34%);color:var(--text);font:14px/1.45 Inter,system-ui,sans-serif}
main{max-width:1700px;margin:auto;padding:24px}.head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:18px}h1{margin:0;font-size:27px;letter-spacing:-.5px}.sub,.muted{color:var(--muted)}.live{display:flex;gap:8px;align-items:center}.dot{width:9px;height:9px;border-radius:50%;background:var(--green);box-shadow:0 0 16px var(--green)}
.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.card,.tablewrap{background:linear-gradient(145deg,#102131,#0b1621);border:1px solid var(--line);border-radius:13px}.card{padding:15px}.label{font-size:12px;color:var(--muted)}.value{font-size:24px;font-weight:750;margin-top:6px}
.tablewrap{margin-top:15px;overflow:auto}table{width:100%;border-collapse:collapse;white-space:nowrap}th,td{padding:12px 10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:middle}th{position:sticky;top:0;background:#102131;color:var(--muted);font-size:12px;font-weight:600;z-index:1}tbody tr:hover{background:#122638}tbody tr:last-child td{border-bottom:0}.name{font-weight:750}.address{font-size:12px;color:var(--muted)}.badge{display:inline-block;border:1px solid currentColor;border-radius:999px;padding:3px 9px;font-size:12px}.ok{color:var(--green)}.warn{color:var(--amber)}.bad{color:var(--red)}.streamcell{line-height:1.55}.streammeta{font-size:12px;color:var(--muted)}.actions{display:flex;gap:6px;align-items:center}
.nodebutton{border:0;background:transparent;padding:0;color:var(--cyan);font-size:15px;font-weight:750}.nodebutton:hover{text-decoration:underline}.clientdetail td{padding:0;background:#071019}.clientpanel{padding:14px 18px;white-space:normal}.clientsummary{margin-bottom:9px;color:var(--muted)}.clienttable{width:100%;white-space:nowrap}.clienttable th,.clienttable td{padding:8px 10px}.clientempty{padding:16px;color:var(--muted)}.uripanel{margin-top:15px}.uri{font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--cyan);white-space:normal;overflow-wrap:anywhere}.right{text-align:right}
button{background:#122738;color:var(--text);border:1px solid #31506a;border-radius:8px;padding:7px 9px;cursor:pointer}button:hover{border-color:var(--cyan)}button.danger{border-color:#7f3442;color:#ff9bab}button.primary{border-color:#277d79;color:#7cf4ed}.weight{display:flex;align-items:center;gap:6px}input{width:58px;background:#08131d;color:var(--text);border:1px solid #31506a;border-radius:7px;padding:7px}
.notice{margin-top:15px;padding:12px 14px;background:#201c0c;border:1px solid #66521f;border-radius:10px;color:#ffd981}.foot{margin-top:15px;color:var(--muted);font-size:12px}
.latency{margin-top:15px;background:linear-gradient(145deg,#102131,#0b1621);border:1px solid var(--line);border-radius:13px;padding:16px}.latencyhead{display:flex;justify-content:space-between;align-items:center;gap:12px}.latencyhead h2{margin:0;font-size:18px}.latencyselect{background:#08131d;color:var(--text);border:1px solid #31506a;border-radius:7px;padding:7px}.pipeline{display:flex;align-items:stretch;gap:7px;margin-top:14px;overflow:auto}.pipe{min-width:180px;flex:1;background:#08131d;border:1px solid #1b3041;border-radius:10px;padding:11px}.pipename{font-size:12px;color:var(--muted)}.pipevalue{font-size:23px;font-weight:750;margin:5px 0}.pipeq{font-size:11px;color:var(--muted);line-height:1.7}.arrow{display:flex;align-items:center;color:var(--cyan);font-size:22px}.chartbox{position:relative;margin-top:13px;border:1px solid #1b3041;border-radius:10px;padding:10px;background:#08131d}.chartlegend{font-size:11px;color:var(--muted);margin-bottom:5px}.chartbox canvas{display:block;width:100%;height:260px}.charttooltip{display:none;position:absolute;z-index:4;pointer-events:none;min-width:180px;padding:9px 11px;border:1px solid #31506a;border-radius:8px;background:#071019eF;box-shadow:0 8px 24px #0008;font:12px/1.65 ui-monospace,SFMono-Regular,Menlo,monospace}.charttooltip.visible{display:block}.chartnote{margin-top:6px;color:var(--muted);font-size:11px}
.eventlog{margin-top:15px;background:linear-gradient(145deg,#102131,#0b1621);border:1px solid var(--line);border-radius:13px;padding:16px}.eventloghead{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-bottom:12px}.eventloghead h2{margin:0;font-size:18px}.wsstates{display:flex;flex-wrap:wrap;gap:8px}.wsstate{border:1px solid currentColor;border-radius:999px;padding:3px 9px;font-size:12px}.eventviewport{height:310px;overflow:auto;border:1px solid #1b3041;border-radius:10px;background:#07111b;scroll-behavior:smooth}.eventrow{display:grid;grid-template-columns:92px 82px 110px minmax(240px,1.7fr) minmax(120px,.8fr) minmax(190px,1.5fr) 90px 74px 90px;gap:10px;align-items:center;padding:10px 12px;border-bottom:1px solid #172a3a;font:12px/1.35 ui-monospace,SFMono-Regular,Menlo,monospace}.eventrow:last-child{border-bottom:0}.eventcolumns{position:sticky;top:0;z-index:2;background:#102131;color:var(--muted);font:600 12px/1.35 Inter,system-ui,sans-serif}.eventrow.new{animation:eventflash 1.1s ease-out}.eventtype{font-weight:800;text-transform:uppercase}.eventtitle,.eventhash{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.eventtitle{color:var(--text);font-family:Inter,system-ui,sans-serif}.eventlatency{font-weight:750}.eventempty{height:100%;min-height:80px;display:grid;place-items:center;color:var(--muted)}@keyframes eventflash{from{background:#174a4d}to{background:transparent}}
/* 单屏 NOC 监控布局：页面不纵向滚动，信息面板各自滚动。 */
body{overflow:hidden}main{max-width:none;width:100%;height:100vh;padding:8px 10px;display:grid;grid-template-columns:minmax(720px,2fr) minmax(430px,1fr);grid-template-rows:36px 58px minmax(300px,1.15fr) minmax(210px,.85fr) 18px;grid-template-areas:"head head" "summary notice" "latency uri" "nodes events" "foot foot";gap:7px}.head{grid-area:head;margin:0;align-items:center}.head h1{font-size:20px}.head .sub{font-size:11px}.summary{grid-area:summary;gap:6px}.card{padding:7px 10px;border-radius:9px}.label{font-size:10px}.value{font-size:18px;margin-top:1px}.notice{grid-area:notice;margin:0;padding:7px 10px;border-radius:9px;font-size:11px;overflow:auto}.notice button{padding:4px 7px}.uripanel{grid-area:uri;margin:0;min-height:0;overflow:auto}.uripanel .clientpanel{padding:8px 10px}.uripanel h2{margin:0;font-size:15px}.clientsummary{margin:2px 0 5px;font-size:10px}.latency{grid-area:latency;margin:0;padding:9px 10px;border-radius:9px;min-height:0;overflow:hidden}.latencyhead h2{font-size:15px}.latencyhead .muted{font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.latencyselect{padding:4px 6px;font-size:11px}.pipeline{gap:4px;margin-top:6px}.pipe{min-width:112px;padding:6px;border-radius:7px}.pipename{font-size:10px}.pipevalue{font-size:17px;margin:1px 0}.pipeq{font-size:9px;line-height:1.45}.arrow{font-size:14px}.chartbox{margin-top:6px;padding:5px}.chartlegend,.chartnote{font-size:9px}.chartbox canvas{height:150px}.nodepanel{grid-area:nodes;margin:0;min-height:0;overflow:auto}.eventlog{grid-area:events;margin:0;padding:8px 10px;min-height:0;overflow:hidden;display:flex;flex-direction:column}.eventloghead{margin-bottom:5px}.eventloghead h2{font-size:15px}.eventloghead .muted,.wsstate{font-size:10px}.wsstate{padding:2px 6px}.eventviewport{height:auto;min-height:0;flex:1}.eventrow{grid-template-columns:70px 60px 72px minmax(160px,1fr) 85px 115px 65px 52px 68px;gap:5px;padding:6px 7px;font-size:10px}.foot{grid-area:foot;margin:0;font-size:9px;overflow:hidden;white-space:nowrap}.tablewrap{border-radius:9px}th,td{padding:7px 6px;font-size:10px}.badge{padding:2px 6px;font-size:10px}.streammeta{font-size:9px}.actions{gap:3px}.actions button,.weight button{padding:3px 5px;font-size:9px}.weight input{width:45px;padding:3px;font-size:9px}
@media(max-width:1180px),(max-height:720px){body{overflow:auto}main{height:auto;min-height:100vh;display:block;padding:10px}.head{margin-bottom:8px}.summary{margin-bottom:8px}.notice,.uripanel,.latency,.eventlog,.nodepanel{margin-top:8px}.chartbox canvas{height:180px}.eventviewport{height:260px}.summary{grid-template-columns:repeat(5,1fr)}}@media(max-width:760px){.summary{grid-template-columns:repeat(2,1fr)}.head{align-items:start;flex-direction:column;height:auto}.pipeline{overflow:auto}.pipe{min-width:145px}}
</style>
</head>
<body><main>
<div class="head"><div><h1>UMA Slave Cluster</h1><div class="sub">预发布控制面 · 43.135.4.241 · 生产流量尚未接入</div></div><div class="live"><span class="dot"></span><span id="refresh">加载中</span></div></div>
<div class="summary" id="summary"></div>
<div class="notice">当前入口仅用于测试。DRAIN只停止新连接；MAINT会立即从负载池摘除节点。节点恢复后可执行渐进回流，每2秒小批量释放超载节点连接。 <button class="primary" id="rebalance" onclick="rebalance()">渐进回流</button></div>
<section class="tablewrap uripanel"><div class="clientpanel"><h2>Worker 接入 URI 统计</h2><div class="muted clientsummary" id="uristatus">正在读取各节点当前连接</div><div style="overflow:auto"><table><thead><tr><th>接入 URI</th><th class="right">当前连接</th><th class="right">占比</th><th class="right">节点数</th><th class="right">独立 Worker IP</th></tr></thead><tbody id="uristats"><tr><td colspan="5" class="clientempty">加载中…</td></tr></tbody></table></div></div></section>
<section class="latency"><div class="latencyhead"><div><h2>WSS 实时延迟流水线</h2><div class="muted" id="latencyage">等待采集器心跳</div></div><div><select class="latencyselect" id="latencycollector" onchange="refresh()"><option value="">自动选择探针</option></select> <select class="latencyselect" id="latencystage" onchange="renderLatency()"><option value="end_to_end">端到端</option><option value="chain_to_master">链上 → Master</option><option value="master_processing">Master 处理</option><option value="master_to_slave">Master → Slave</option><option value="slave_processing">Slave 处理</option><option value="slave_to_client">Slave → 客户端</option></select> <select class="latencyselect" id="latencynode" onchange="renderLatency()"><option value="overall">集群整体</option></select></div></div><div class="pipeline" id="pipeline"></div><div class="chartbox"><div class="chartlegend"><span id="chartstage">端到端</span>趋势：<span style="color:#43dc8b">P50</span> · <span style="color:#ffbf5a">P95</span> · <span style="color:#ff657a">P99</span></div><canvas id="latencychart"></canvas><div class="charttooltip" id="charttooltip"></div><div class="chartnote">纵轴固定 0–1000ms；超过 1000ms 的点压在图顶，悬停显示真实值。空窗口只更新探针状态，不绘制为 0ms。</div></div></section>
<section class="eventlog"><div class="eventloghead"><div><h2>WSS 实时事件</h2><div class="muted">浏览器直连 · 最新在上 · 最近 10 条</div></div><div class="wsstates"><span class="wsstate warn" id="ws-proposed">Proposed 连接中</span><span class="wsstate warn" id="ws-disputed">Disputed 连接中</span></div></div><div class="eventviewport" id="eventviewport"><div class="eventempty">等待 WSS 事件…</div></div></section>
<div class="tablewrap nodepanel"><table>
<thead><tr><th>节点</th><th>程序版本</th><th>状态</th><th>连接</th><th>权重</th><th>运行时间</th><th>HTTP缓存</th><th>Proposed</th><th>Disputed</th><th>流量操作</th><th>权重设置</th></tr></thead>
<tbody id="nodes"></tbody>
</table></div>
<div class="foot" id="foot"></div>
</main>
<script>
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const card=(l,v,c='')=>'<div class="card"><div class="label">'+l+'</div><div class="value '+c+'">'+v+'</div></div>';
const latencyStages=[['chain_to_master','链上 → Master'],['master_processing','Master 处理'],['master_to_slave','Master → Slave'],['slave_processing','Slave 处理'],['slave_to_client','Slave → 客户端'],['end_to_end','端到端']];
const latencyStageNames=Object.fromEntries(latencyStages);
let latencyData={latest:{},history:[]};
const ms=v=>v===undefined||v===null?'—':v+' ms';
function renderLatency(){let latest=latencyData.latest||{},history=latencyData.history||[],lastSample=history.length?history[history.length-1]:null,sel=document.getElementById('latencynode').value,stage=document.getElementById('latencystage').value,data=sel==='overall'?(Object.keys(latest.overall||{}).length?latest.overall:(lastSample?.overall||{})):(latest.nodes||{})[sel],pipe=document.getElementById('pipeline'),collector=(latencyData.collectors||[]).find(x=>x.collector_id===latencyData.selected_collector_id),windowSummary=lastSample?(' · 窗口 n='+(lastSample.sample_count||0)+' / batch事件 '+(lastSample.batch_event_count||0)+' / batch帧 '+(lastSample.batch_count||0)):'';document.getElementById('chartstage').textContent=latencyStageNames[stage]||stage;document.getElementById('latencyage').textContent=collector?(collector.collector_id+' · '+collector.status+' · '+(collector.encoding||'待识别')+' v'+(collector.schema_version||'—')+' · 心跳 '+Math.max(0,Math.round((collector.report_age_ms||0)/1000))+' 秒前 · 最近样本 '+(lastSample?new Date(lastSample.generated_at_ms).toLocaleTimeString('zh-CN',{hour12:false}):'暂无')+windowSummary+' · 解码错误 '+(collector.decode_errors||0)):'等待采集器心跳';if(!data||!Object.keys(data).length){pipe.innerHTML='<div class="muted">探针心跳正常，尚无有效 realtime 样本</div>';drawLatency(history,stage);return}pipe.innerHTML=latencyStages.map((x,i)=>{let q=data[x[0]]||{};return '<div class="pipe"><div class="pipename">'+x[1]+'</div><div class="pipevalue">'+ms(q.p95_ms)+'</div><div class="pipeq">P50 '+ms(q.p50_ms)+' · P90 '+ms(q.p90_ms)+'<br>P95 '+ms(q.p95_ms)+' · P99 '+ms(q.p99_ms)+'<br>Max '+ms(q.max_ms)+' · 窗口n='+(q.count||0)+(q.clock_adjusted?'<br><span class="warn">时钟校正 '+q.clock_adjusted+'</span>':'')+'</div></div>'+(i<latencyStages.length-1?'<div class="arrow">›</div>':'')}).join('');drawLatency(sel==='overall'?history:[],stage)}
let latencyChartPoints=[];
function drawLatency(history,stage='end_to_end'){let c=document.getElementById('latencychart'),r=c.getBoundingClientRect(),d=devicePixelRatio||1,w=r.width,h=260,L=54,R=18,T=16,B=34,max=1000,rows=history.slice(-120),g=c.getContext('2d');c.width=Math.max(1,w*d);c.height=h*d;g.scale(d,d);g.clearRect(0,0,w,h);let x=i=>L+(w-L-R)*(rows.length<2?1:i/(rows.length-1)),y=v=>h-B-(h-T-B)*Math.min(max,Math.max(0,v))/max;g.font='11px system-ui';g.textBaseline='middle';for(let v=0;v<=max;v+=250){let yy=y(v);g.strokeStyle='#203548';g.lineWidth=1;g.beginPath();g.moveTo(L,yy);g.lineTo(w-R,yy);g.stroke();g.fillStyle='#8ba1b1';g.textAlign='right';g.fillText(v+'ms',L-7,yy)}let xStep=Math.max(1,Math.ceil(rows.length/6));rows.forEach((row,i)=>{if(i%xStep&&i!==rows.length-1)return;let xx=x(i),stamp=Number(row.generated_at_ms)||0,label=stamp?new Date(stamp).toLocaleTimeString('zh-CN',{hour12:false,hour:'2-digit',minute:'2-digit'}):'—';g.strokeStyle='#142738';g.beginPath();g.moveTo(xx,T);g.lineTo(xx,h-B);g.stroke();g.fillStyle='#8ba1b1';g.textAlign='center';g.textBaseline='top';g.fillText(label,xx,h-B+8)});latencyChartPoints=rows.map((row,i)=>({x:x(i),row,stage}));[['p50_ms','#43dc8b'],['p95_ms','#ffbf5a'],['p99_ms','#ff657a']].forEach(([key,color])=>{g.strokeStyle=color;g.lineWidth=2;g.beginPath();let drawn=false;rows.forEach((row,i)=>{let v=row.overall?.[stage]?.[key];if(!Number.isFinite(v))return;let xx=x(i),yy=y(v);if(!drawn){g.moveTo(xx,yy);drawn=true}else g.lineTo(xx,yy)});g.stroke();g.fillStyle=color;rows.forEach((row,i)=>{let v=row.overall?.[stage]?.[key];if(!Number.isFinite(v))return;g.beginPath();g.arc(x(i),y(v),3,0,Math.PI*2);g.fill()})})}
function showLatencyTooltip(event){let c=document.getElementById('latencychart'),tip=document.getElementById('charttooltip');if(!latencyChartPoints.length){tip.classList.remove('visible');return}let rect=c.getBoundingClientRect(),mx=event.clientX-rect.left,point=latencyChartPoints.reduce((best,p)=>Math.abs(p.x-mx)<Math.abs(best.x-mx)?p:best),q=point.row.overall?.[point.stage]||{},stamp=Number(point.row.generated_at_ms)||0,refs=(point.row.batch_refs||[]).join(', ')||'—';tip.innerHTML='<strong>'+(stamp?new Date(stamp).toLocaleString('zh-CN',{hour12:false}):'时间未知')+'</strong><br>阶段：'+esc(latencyStageNames[point.stage]||point.stage)+'<br><span style="color:#43dc8b">P50 '+ms(q.p50_ms)+'</span><br><span style="color:#ffbf5a">P95 '+ms(q.p95_ms)+'</span><br><span style="color:#ff657a">P99 '+ms(q.p99_ms)+'</span><br>Max '+ms(q.max_ms)+' · 窗口 n='+(point.row.sample_count??q.count??0)+'<br>batch帧 '+(point.row.batch_count||0)+' · batch事件 '+(point.row.batch_event_count||0)+'<br>batch ID/part：'+esc(refs);tip.style.left=Math.min(rect.width-280,Math.max(8,point.x+12))+'px';tip.style.top='38px';tip.classList.add('visible')}
document.addEventListener('mousemove',e=>{if(e.target.id==='latencychart')showLatencyTooltip(e)});document.addEventListener('mouseout',e=>{if(e.target.id==='latencychart')document.getElementById('charttooltip').classList.remove('visible')});
const stream=s=>'<div class="streamcell"><span class="'+(s?.upstream_connected?'ok':'bad')+'">'+(s?.upstream_connected?'上游在线':'上游断线')+'</span><div class="streammeta">下游 '+(s?.subscribers??0)+' · 收包 '+(s?.messages_received??0)+'<br>慢客户端 '+(s?.slow_clients_disconnected??0)+'</div></div>';
const wsEvents=[];
const marketTitles=new Map();
const short=v=>{v=String(v||'');return v.length>18?v.slice(0,10)+'…'+v.slice(-6):v||'—'};
function eventLatency(e){let now=Date.now(),base=Number(e.upstream_received_at_ms)||Number(e.timestamp)*1000;if(!base)return '—';let value=now-base;return value<1000?value+' ms':(value/1000).toFixed(2)+' s'}
function eventTitle(e){return marketTitles.get(e.condition_id)||e.title||e.question||'标题查询中…'}
const eventColumns='<div class="eventrow eventcolumns"><span title="浏览器收到该条 WSS 消息的本地时间">接收时间</span><span title="propose 或 dispute">事件类型</span><span title="realtime 实时事件或 backfill 补发事件">来源</span><span title="Polymarket 市场问题标题">标题</span><span title="Polymarket 市场 ID">Market ID</span><span title="Polymarket Condition ID">Condition ID</span><span title="链上区块高度">区块</span><span title="UMA 报价结果">价格</span><span title="Master 收到链上事件至当前浏览器展示的耗时">端到端延迟</span></div>';
function renderWSEvents(){let viewport=document.getElementById('eventviewport');if(!wsEvents.length){viewport.innerHTML=eventColumns+'<div class="eventempty">等待 WSS 事件…</div>';return}viewport.innerHTML=eventColumns+wsEvents.map((e,i)=>'<div class="eventrow '+(i===0?'new':'')+'"><span>'+new Date(e.client_received_at_ms).toLocaleTimeString()+'</span><span class="eventtype '+(e.event_type==='dispute'?'bad':'ok')+'">'+esc(e.event_type)+'</span><span>'+esc(e.source||'realtime')+'</span><span class="eventtitle" title="'+esc(eventTitle(e))+'">'+esc(eventTitle(e))+'</span><span class="eventhash" title="'+esc(e.market_id)+'">M '+esc(e.market_id||'—')+'</span><span class="eventhash" title="'+esc(e.condition_id)+'">'+esc(short(e.condition_id))+'</span><span>#'+esc(e.block_number)+'</span><span>'+esc(e.price||'—')+'</span><span class="eventlatency">'+eventLatency(e)+'</span></div>').join('');viewport.scrollTop=0}
async function ensureEventTitle(e){let id=e.condition_id;if(!id||marketTitles.has(id))return;marketTitles.set(id,'标题查询中…');try{let r=await fetch('/api/market-title?condition_id='+encodeURIComponent(id),{cache:'force-cache'}),d=await r.json();marketTitles.set(id,d.title||'未找到标题')}catch(_){marketTitles.set(id,'标题查询失败')}renderWSEvents()}
function setWSState(kind,state,text){let el=document.getElementById('ws-'+kind);el.className='wsstate '+state;el.textContent=kind[0].toUpperCase()+kind.slice(1)+' '+text}
function connectEventWS(kind){let scheme=location.protocol==='https:'?'wss:':'ws:',url=scheme+'//'+location.hostname+':8081/uma/v1/ws/'+kind,retry=250,socket;function open(){setWSState(kind,'warn','连接中');socket=new WebSocket(url);socket.onopen=()=>{retry=250;setWSState(kind,'ok','在线')};socket.onmessage=message=>{try{let event=JSON.parse(message.data);event.client_received_at_ms=Date.now();wsEvents.unshift(event);if(wsEvents.length>10)wsEvents.pop();renderWSEvents();ensureEventTitle(event)}catch(e){}};socket.onerror=()=>socket.close();socket.onclose=()=>{setWSState(kind,'bad','重连中');setTimeout(open,retry);retry=Math.min(retry*2,5000)}}open()}
const expandedNodes=new Set();
function nodeHTML(n){let h=n.health||{},ss=h.streams||{},status=n.healthy&&n.haproxy_status.startsWith('UP')?'ok':n.haproxy_status==='DRAIN'?'warn':'bad',open=expandedNodes.has(n.id);return '<tr><td><button class="nodebutton" onclick="toggleClients(\''+n.id+'\')">'+(open?'▾ ':'▸ ')+esc(n.id)+'</button><div class="address">'+esc(n.address)+'</div></td><td><span class="badge">'+esc(h.version||'未知')+'</span></td><td><span class="badge '+status+'">'+esc(n.haproxy_status)+'</span></td><td>'+n.connections+'</td><td>'+n.weight+'</td><td>'+Math.floor((h.uptime_seconds||0)/60)+'m</td><td>'+(h.http_cache?.entries??0)+'/'+(h.http_cache?.capacity??0)+'</td><td>'+stream(ss['/uma/v1/ws/proposed'])+'</td><td>'+stream(ss['/uma/v1/ws/disputed'])+'</td><td><div class="actions"><button class="primary" onclick="act(\''+n.id+'\',\'ready\')">恢复并回流</button><button onclick="act(\''+n.id+'\',\'drain\')">摘流</button><button onclick="act(\''+n.id+'\',\'maintenance\')">维护</button><button class="danger" onclick="act(\''+n.id+'\',\'force\')">强制</button></div></td><td><span class="weight"><input id="w-'+n.id+'" type="number" min="0" max="100" value="'+n.weight+'"><button onclick="weight(\''+n.id+'\')">设置</button></span></td></tr><tr class="clientdetail" id="clients-row-'+n.id+'" style="display:'+(open?'table-row':'none')+'"><td colspan="11"><div class="clientpanel" id="clients-'+n.id+'">'+(open?'<span class="muted">正在读取客户端…</span>':'')+'</div></td></tr>'}
function toggleClients(id){if(expandedNodes.has(id))expandedNodes.delete(id);else expandedNodes.add(id);refresh()}
async function loadClients(id){let box=document.getElementById('clients-'+id);if(!box)return;try{let r=await fetch('/api/nodes/'+encodeURIComponent(id)+'/clients',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'读取失败');let rows=d.clients||[];box.innerHTML='<div class="clientsummary">当前 '+rows.length+' 条下游 WSS 连接 · 每3秒刷新</div>'+(rows.length?'<div style="overflow:auto"><table class="clienttable"><thead><tr><th>连接ID</th><th>客户端IP</th><th>端口</th><th>订阅流</th><th>连接时间</th><th>持续时间</th></tr></thead><tbody>'+rows.map(c=>'<tr><td>'+esc(c.id)+'</td><td>'+esc(c.ip)+'</td><td>'+esc(c.port||'—')+'</td><td>'+esc((c.stream||'').replace('/uma/v1/ws/',''))+'</td><td>'+new Date(c.connected_at_ms).toLocaleString()+'</td><td>'+Math.max(0,c.connected_seconds)+'s</td></tr>').join('')+'</tbody></table></div>':'<div class="clientempty">当前没有下游连接</div>')}catch(e){box.innerHTML='<span class="bad">'+esc(e.message)+'</span>'}}
function loadExpandedClients(){expandedNodes.forEach(loadClients)}
async function loadURIStats(nodes){let status=document.getElementById('uristatus'),body=document.getElementById('uristats');try{let results=await Promise.all(nodes.map(async n=>{let r=await fetch('/api/nodes/'+encodeURIComponent(n.id)+'/clients',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(n.id+': '+(d.error||'读取失败'));return{node:n.id,clients:d.clients||[]}})),stats=new Map(),total=0;results.forEach(result=>result.clients.forEach(c=>{let uri=c.stream||'未识别',row=stats.get(uri);if(!row){row={uri,count:0,nodes:new Set(),ips:new Set()};stats.set(uri,row)}row.count++;total++;row.nodes.add(result.node);if(c.ip)row.ips.add(c.ip)}));let rows=[...stats.values()].sort((a,b)=>b.count-a.count||a.uri.localeCompare(b.uri));status.textContent='集群当前 '+total+' 条 Worker WSS 连接 · '+rows.length+' 种接入 URI · 每3秒刷新';body.innerHTML=rows.length?rows.map(x=>'<tr><td class="uri">'+esc(x.uri)+'</td><td class="right">'+x.count+'</td><td class="right">'+(total?100*x.count/total:0).toFixed(1)+'%</td><td class="right">'+x.nodes.size+'</td><td class="right">'+x.ips.size+'</td></tr>').join(''):'<tr><td colspan="5" class="clientempty">当前没有 Worker WSS 连接</td></tr>'}catch(e){status.textContent='URI 统计读取失败';body.innerHTML='<tr><td colspan="5" class="bad">'+esc(e.message)+'</td></tr>'}}
async function act(id,action,value=0){if((action==='force')&&!confirm('确认断开 '+id+' 的全部现有连接并摘除节点？'))return;let r=await fetch('/api/nodes/'+encodeURIComponent(id)+'/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,value})});if(!r.ok)alert(await r.text());await refresh()}
function weight(id){let v=Number(document.getElementById('w-'+id).value);act(id,'weight',v)}
async function rebalance(){if(!confirm('确认渐进释放超载节点连接并重新均衡？客户端需要支持自动重连。'))return;let r=await fetch('/api/rebalance',{method:'POST'});if(!r.ok)alert(await r.text());await refresh()}
async function refresh(){try{let collectorSelect=document.getElementById('latencycollector'),wanted=collectorSelect.value,latencyURL='/api/latency'+(wanted?'?collector_id='+encodeURIComponent(wanted):''),[r,lr]=await Promise.all([fetch('/api/status',{cache:'no-store'}),fetch(latencyURL,{cache:'no-store'})]),d=await r.json();latencyData=await lr.json();let collectors=latencyData.collectors||[],selectedCollector=wanted||latencyData.selected_collector_id||'';collectorSelect.innerHTML='<option value="">自动选择探针</option>'+collectors.map(x=>'<option value="'+esc(x.collector_id)+'">'+esc(x.collector_id)+' · '+esc(x.status)+'</option>').join('');collectorSelect.value=collectors.some(x=>x.collector_id===selectedCollector)?selectedCollector:'';let nodes=d.nodes||[],healthy=nodes.filter(x=>x.healthy).length,connections=nodes.reduce((a,x)=>a+x.connections,0),upstreams=nodes.reduce((a,x)=>a+Object.values(x.health?.streams||{}).filter(s=>s.upstream_connected).length,0),rb=document.getElementById('rebalance'),select=document.getElementById('latencynode'),selected=select.value,nodeIDs=Object.keys(latencyData.latest?.nodes||{});select.innerHTML='<option value="overall">集群整体</option>'+nodeIDs.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('');select.value=nodeIDs.includes(selected)||selected==='overall'?selected:'overall';rb.disabled=!!d.rebalancing;rb.textContent=d.rebalancing?'回流中…':'渐进回流';document.getElementById('summary').innerHTML=card('节点在线',healthy+'/'+nodes.length,healthy===nodes.length?'ok':'bad')+card('测试入口连接',connections)+card('Master上游WSS',upstreams,upstreams===nodes.length*4?'ok':'warn')+card('接流节点',nodes.filter(x=>x.haproxy_status.startsWith('UP')).length)+card('控制器运行',Math.floor(d.uptime_seconds/60)+'m');document.getElementById('nodes').innerHTML=nodes.map(nodeHTML).join('');loadExpandedClients();loadURIStats(nodes);renderLatency();document.getElementById('refresh').textContent=d.rebalancing?'正在渐进回流':'控制面在线';document.getElementById('foot').textContent='每3秒刷新 · '+new Date(d.generated_at_ms).toLocaleString()+(d.haproxy_error?' · HAProxy: '+d.haproxy_error:'')}catch(e){document.getElementById('refresh').textContent='读取失败'}}renderWSEvents();connectEventWS('proposed');connectEventWS('disputed');refresh();setInterval(refresh,3000);addEventListener('resize',()=>renderLatency());
</script></body></html>`
