// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/compact_trade_v5.proto

package wirev5

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompactTradeBatch struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion      uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	PayloadFormat      string                 `protobuf:"bytes,2,opt,name=payload_format,json=payloadFormat,proto3" json:"payload_format,omitempty"`
	BatchId            string                 `protobuf:"bytes,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	BatchPart          uint32                 `protobuf:"varint,4,opt,name=batch_part,json=batchPart,proto3" json:"batch_part,omitempty"`
	ServerSentAtUs     int64                  `protobuf:"varint,5,opt,name=server_sent_at_us,json=serverSentAtUs,proto3" json:"server_sent_at_us,omitempty"`
	SlaveReceivedAtUs  int64                  `protobuf:"varint,6,opt,name=slave_received_at_us,json=slaveReceivedAtUs,proto3" json:"slave_received_at_us,omitempty"`
	SlaveBroadcastAtUs int64                  `protobuf:"varint,7,opt,name=slave_broadcast_at_us,json=slaveBroadcastAtUs,proto3" json:"slave_broadcast_at_us,omitempty"`
	Events             []*CompactTradeEvent   `protobuf:"bytes,8,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompactTradeBatch) Reset() {
	*x = CompactTradeBatch{}
	mi := &file_api_proto_compact_trade_v5_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactTradeBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactTradeBatch) ProtoMessage() {}

func (x *CompactTradeBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_compact_trade_v5_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactTradeBatch.ProtoReflect.Descriptor instead.
func (*CompactTradeBatch) Descriptor() ([]byte, []int) {
	return file_api_proto_compact_trade_v5_proto_rawDescGZIP(), []int{0}
}

func (x *CompactTradeBatch) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *CompactTradeBatch) GetPayloadFormat() string {
	if x != nil {
		return x.PayloadFormat
	}
	return ""
}

func (x *CompactTradeBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *CompactTradeBatch) GetBatchPart() uint32 {
	if x != nil {
		return x.BatchPart
	}
	return 0
}

func (x *CompactTradeBatch) GetServerSentAtUs() int64 {
	if x != nil {
		return x.ServerSentAtUs
	}
	return 0
}

func (x *CompactTradeBatch) GetSlaveReceivedAtUs() int64 {
	if x != nil {
		return x.SlaveReceivedAtUs
	}
	return 0
}

func (x *CompactTradeBatch) GetSlaveBroadcastAtUs() int64 {
	if x != nil {
		return x.SlaveBroadcastAtUs
	}
	return 0
}

func (x *CompactTradeBatch) GetEvents() []*CompactTradeEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type CompactTradeEvent struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Type                      string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ProcessingKey             string                 `protobuf:"bytes,2,opt,name=processing_key,json=processingKey,proto3" json:"processing_key,omitempty"`
	Source                    string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	ConditionId               string                 `protobuf:"bytes,4,opt,name=condition_id,json=conditionId,proto3" json:"condition_id,omitempty"`
	MarketId                  string                 `protobuf:"bytes,5,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	ProposedPrice             string                 `protobuf:"bytes,6,opt,name=proposed_price,json=proposedPrice,proto3" json:"proposed_price,omitempty"`
	BlockNumber               uint64                 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TransactionHash           string                 `protobuf:"bytes,8,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	LogIndex                  int32                  `protobuf:"varint,9,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	Timestamp                 int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Question                  string                 `protobuf:"bytes,11,opt,name=question,proto3" json:"question,omitempty"`
	EventId                   string                 `protobuf:"bytes,12,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Title                     string                 `protobuf:"bytes,13,opt,name=title,proto3" json:"title,omitempty"`
	TagIds                    []string               `protobuf:"bytes,14,rep,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	SportsMarketType          string                 `protobuf:"bytes,15,opt,name=sports_market_type,json=sportsMarketType,proto3" json:"sports_market_type,omitempty"`
	Category                  string                 `protobuf:"bytes,16,opt,name=category,proto3" json:"category,omitempty"`
	ChainTimestampMs          int64                  `protobuf:"varint,17,opt,name=chain_timestamp_ms,json=chainTimestampMs,proto3" json:"chain_timestamp_ms,omitempty"`
	MasterReceivedAtUs        int64                  `protobuf:"varint,18,opt,name=master_received_at_us,json=masterReceivedAtUs,proto3" json:"master_received_at_us,omitempty"`
	MasterQueueEnterAtUs      int64                  `protobuf:"varint,19,opt,name=master_queue_enter_at_us,json=masterQueueEnterAtUs,proto3" json:"master_queue_enter_at_us,omitempty"`
	MasterProcessingStartAtUs int64                  `protobuf:"varint,20,opt,name=master_processing_start_at_us,json=masterProcessingStartAtUs,proto3" json:"master_processing_start_at_us,omitempty"`
	CatalogLookupDoneAtUs     int64                  `protobuf:"varint,21,opt,name=catalog_lookup_done_at_us,json=catalogLookupDoneAtUs,proto3" json:"catalog_lookup_done_at_us,omitempty"`
	MasterBroadcastAtUs       int64                  `protobuf:"varint,22,opt,name=master_broadcast_at_us,json=masterBroadcastAtUs,proto3" json:"master_broadcast_at_us,omitempty"`
	MappingWaitMs             int64                  `protobuf:"varint,23,opt,name=mapping_wait_ms,json=mappingWaitMs,proto3" json:"mapping_wait_ms,omitempty"`
	CatalogWaitMs             int64                  `protobuf:"varint,24,opt,name=catalog_wait_ms,json=catalogWaitMs,proto3" json:"catalog_wait_ms,omitempty"`
	ReplayReadyAtMs           int64                  `protobuf:"varint,25,opt,name=replay_ready_at_ms,json=replayReadyAtMs,proto3" json:"replay_ready_at_ms,omitempty"`
	Market                    *CompactTradeMarket    `protobuf:"bytes,26,opt,name=market,proto3" json:"market,omitempty"`
	Tokens                    []*CompactTradeToken   `protobuf:"bytes,27,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CompactTradeEvent) Reset() {
	*x = CompactTradeEvent{}
	mi := &file_api_proto_compact_trade_v5_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactTradeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactTradeEvent) ProtoMessage() {}

func (x *CompactTradeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_compact_trade_v5_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactTradeEvent.ProtoReflect.Descriptor instead.
func (*CompactTradeEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_compact_trade_v5_proto_rawDescGZIP(), []int{1}
}

func (x *CompactTradeEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CompactTradeEvent) GetProcessingKey() string {
	if x != nil {
		return x.ProcessingKey
	}
	return ""
}

func (x *CompactTradeEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CompactTradeEvent) GetConditionId() string {
	if x != nil {
		return x.ConditionId
	}
	return ""
}

func (x *CompactTradeEvent) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *CompactTradeEvent) GetProposedPrice() string {
	if x != nil {
		return x.ProposedPrice
	}
	return ""
}

func (x *CompactTradeEvent) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *CompactTradeEvent) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *CompactTradeEvent) GetLogIndex() int32 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *CompactTradeEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CompactTradeEvent) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *CompactTradeEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CompactTradeEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CompactTradeEvent) GetTagIds() []string {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *CompactTradeEvent) GetSportsMarketType() string {
	if x != nil {
		return x.SportsMarketType
	}
	return ""
}

func (x *CompactTradeEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CompactTradeEvent) GetChainTimestampMs() int64 {
	if x != nil {
		return x.ChainTimestampMs
	}
	return 0
}

func (x *CompactTradeEvent) GetMasterReceivedAtUs() int64 {
	if x != nil {
		return x.MasterReceivedAtUs
	}
	return 0
}

func (x *CompactTradeEvent) GetMasterQueueEnterAtUs() int64 {
	if x != nil {
		return x.MasterQueueEnterAtUs
	}
	return 0
}

func (x *CompactTradeEvent) GetMasterProcessingStartAtUs() int64 {
	if x != nil {
		return x.MasterProcessingStartAtUs
	}
	return 0
}

func (x *CompactTradeEvent) GetCatalogLookupDoneAtUs() int64 {
	if x != nil {
		return x.CatalogLookupDoneAtUs
	}
	return 0
}

func (x *CompactTradeEvent) GetMasterBroadcastAtUs() int64 {
	if x != nil {
		return x.MasterBroadcastAtUs
	}
	return 0
}

func (x *CompactTradeEvent) GetMappingWaitMs() int64 {
	if x != nil {
		return x.MappingWaitMs
	}
	return 0
}

func (x *CompactTradeEvent) GetCatalogWaitMs() int64 {
	if x != nil {
		return x.CatalogWaitMs
	}
	return 0
}

func (x *CompactTradeEvent) GetReplayReadyAtMs() int64 {
	if x != nil {
		return x.ReplayReadyAtMs
	}
	return 0
}

func (x *CompactTradeEvent) GetMarket() *CompactTradeMarket {
	if x != nil {
		return x.Market
	}
	return nil
}

func (x *CompactTradeEvent) GetTokens() []*CompactTradeToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type CompactTradeMarket struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Active                bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Closed                bool                   `protobuf:"varint,2,opt,name=closed,proto3" json:"closed,omitempty"`
	AcceptingOrders       bool                   `protobuf:"varint,3,opt,name=accepting_orders,json=acceptingOrders,proto3" json:"accepting_orders,omitempty"`
	EnableOrderBook       bool                   `protobuf:"varint,4,opt,name=enable_order_book,json=enableOrderBook,proto3" json:"enable_order_book,omitempty"`
	Slug                  string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	UmaResolutionStatus   string                 `protobuf:"bytes,6,opt,name=uma_resolution_status,json=umaResolutionStatus,proto3" json:"uma_resolution_status,omitempty"`
	UmaResolutionStatuses []string               `protobuf:"bytes,7,rep,name=uma_resolution_statuses,json=umaResolutionStatuses,proto3" json:"uma_resolution_statuses,omitempty"`
	TakerBaseFee          int32                  `protobuf:"varint,8,opt,name=taker_base_fee,json=takerBaseFee,proto3" json:"taker_base_fee,omitempty"`
	UpdatedAtMs           int64                  `protobuf:"varint,9,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	CatalogAgeMs          int64                  `protobuf:"varint,10,opt,name=catalog_age_ms,json=catalogAgeMs,proto3" json:"catalog_age_ms,omitempty"`
	TickSize              *float64               `protobuf:"fixed64,11,opt,name=tick_size,json=tickSize,proto3,oneof" json:"tick_size,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CompactTradeMarket) Reset() {
	*x = CompactTradeMarket{}
	mi := &file_api_proto_compact_trade_v5_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactTradeMarket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactTradeMarket) ProtoMessage() {}

func (x *CompactTradeMarket) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_compact_trade_v5_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactTradeMarket.ProtoReflect.Descriptor instead.
func (*CompactTradeMarket) Descriptor() ([]byte, []int) {
	return file_api_proto_compact_trade_v5_proto_rawDescGZIP(), []int{2}
}

func (x *CompactTradeMarket) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *CompactTradeMarket) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *CompactTradeMarket) GetAcceptingOrders() bool {
	if x != nil {
		return x.AcceptingOrders
	}
	return false
}

func (x *CompactTradeMarket) GetEnableOrderBook() bool {
	if x != nil {
		return x.EnableOrderBook
	}
	return false
}

func (x *CompactTradeMarket) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CompactTradeMarket) GetUmaResolutionStatus() string {
	if x != nil {
		return x.UmaResolutionStatus
	}
	return ""
}

func (x *CompactTradeMarket) GetUmaResolutionStatuses() []string {
	if x != nil {
		return x.UmaResolutionStatuses
	}
	return nil
}

func (x *CompactTradeMarket) GetTakerBaseFee() int32 {
	if x != nil {
		return x.TakerBaseFee
	}
	return 0
}

func (x *CompactTradeMarket) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

func (x *CompactTradeMarket) GetCatalogAgeMs() int64 {
	if x != nil {
		return x.CatalogAgeMs
	}
	return 0
}

func (x *CompactTradeMarket) GetTickSize() float64 {
	if x != nil && x.TickSize != nil {
		return *x.TickSize
	}
	return 0
}

type CompactTradeToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Outcome       string                 `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	OutcomePrice  float64                `protobuf:"fixed64,3,opt,name=outcome_price,json=outcomePrice,proto3" json:"outcome_price,omitempty"`
	UmaPrice      *float64               `protobuf:"fixed64,4,opt,name=uma_price,json=umaPrice,proto3,oneof" json:"uma_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactTradeToken) Reset() {
	*x = CompactTradeToken{}
	mi := &file_api_proto_compact_trade_v5_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactTradeToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactTradeToken) ProtoMessage() {}

func (x *CompactTradeToken) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_compact_trade_v5_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactTradeToken.ProtoReflect.Descriptor instead.
func (*CompactTradeToken) Descriptor() ([]byte, []int) {
	return file_api_proto_compact_trade_v5_proto_rawDescGZIP(), []int{3}
}

func (x *CompactTradeToken) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *CompactTradeToken) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *CompactTradeToken) GetOutcomePrice() float64 {
	if x != nil {
		return x.OutcomePrice
	}
	return 0
}

func (x *CompactTradeToken) GetUmaPrice() float64 {
	if x != nil && x.UmaPrice != nil {
		return *x.UmaPrice
	}
	return 0
}

var File_api_proto_compact_trade_v5_proto protoreflect.FileDescriptor

const file_api_proto_compact_trade_v5_proto_rawDesc = "" +
	"\n" +
	" api/proto/compact_trade_v5.proto\x12\x0fpolyuma.wire.v5\"\xe6\x02\n" +
	"\x11CompactTradeBatch\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12%\n" +
	"\x0epayload_format\x18\x02 \x01(\tR\rpayloadFormat\x12\x19\n" +
	"\bbatch_id\x18\x03 \x01(\tR\abatchId\x12\x1d\n" +
	"\n" +
	"batch_part\x18\x04 \x01(\rR\tbatchPart\x12)\n" +
	"\x11server_sent_at_us\x18\x05 \x01(\x03R\x0eserverSentAtUs\x12/\n" +
	"\x14slave_received_at_us\x18\x06 \x01(\x03R\x11slaveReceivedAtUs\x121\n" +
	"\x15slave_broadcast_at_us\x18\a \x01(\x03R\x12slaveBroadcastAtUs\x12:\n" +
	"\x06events\x18\b \x03(\v2\".polyuma.wire.v5.CompactTradeEventR\x06events\"\xc6\b\n" +
	"\x11CompactTradeEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12%\n" +
	"\x0eprocessing_key\x18\x02 \x01(\tR\rprocessingKey\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12!\n" +
	"\fcondition_id\x18\x04 \x01(\tR\vconditionId\x12\x1b\n" +
	"\tmarket_id\x18\x05 \x01(\tR\bmarketId\x12%\n" +
	"\x0eproposed_price\x18\x06 \x01(\tR\rproposedPrice\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12)\n" +
	"\x10transaction_hash\x18\b \x01(\tR\x0ftransactionHash\x12\x1b\n" +
	"\tlog_index\x18\t \x01(\x05R\blogIndex\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bquestion\x18\v \x01(\tR\bquestion\x12\x19\n" +
	"\bevent_id\x18\f \x01(\tR\aeventId\x12\x14\n" +
	"\x05title\x18\r \x01(\tR\x05title\x12\x17\n" +
	"\atag_ids\x18\x0e \x03(\tR\x06tagIds\x12,\n" +
	"\x12sports_market_type\x18\x0f \x01(\tR\x10sportsMarketType\x12\x1a\n" +
	"\bcategory\x18\x10 \x01(\tR\bcategory\x12,\n" +
	"\x12chain_timestamp_ms\x18\x11 \x01(\x03R\x10chainTimestampMs\x121\n" +
	"\x15master_received_at_us\x18\x12 \x01(\x03R\x12masterReceivedAtUs\x126\n" +
	"\x18master_queue_enter_at_us\x18\x13 \x01(\x03R\x14masterQueueEnterAtUs\x12@\n" +
	"\x1dmaster_processing_start_at_us\x18\x14 \x01(\x03R\x19masterProcessingStartAtUs\x128\n" +
	"\x19catalog_lookup_done_at_us\x18\x15 \x01(\x03R\x15catalogLookupDoneAtUs\x123\n" +
	"\x16master_broadcast_at_us\x18\x16 \x01(\x03R\x13masterBroadcastAtUs\x12&\n" +
	"\x0fmapping_wait_ms\x18\x17 \x01(\x03R\rmappingWaitMs\x12&\n" +
	"\x0fcatalog_wait_ms\x18\x18 \x01(\x03R\rcatalogWaitMs\x12+\n" +
	"\x12replay_ready_at_ms\x18\x19 \x01(\x03R\x0freplayReadyAtMs\x12;\n" +
	"\x06market\x18\x1a \x01(\v2#.polyuma.wire.v5.CompactTradeMarketR\x06market\x12:\n" +
	"\x06tokens\x18\x1b \x03(\v2\".polyuma.wire.v5.CompactTradeTokenR\x06tokens\"\xbb\x03\n" +
	"\x12CompactTradeMarket\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x16\n" +
	"\x06closed\x18\x02 \x01(\bR\x06closed\x12)\n" +
	"\x10accepting_orders\x18\x03 \x01(\bR\x0facceptingOrders\x12*\n" +
	"\x11enable_order_book\x18\x04 \x01(\bR\x0fenableOrderBook\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x122\n" +
	"\x15uma_resolution_status\x18\x06 \x01(\tR\x13umaResolutionStatus\x126\n" +
	"\x17uma_resolution_statuses\x18\a \x03(\tR\x15umaResolutionStatuses\x12$\n" +
	"\x0etaker_base_fee\x18\b \x01(\x05R\ftakerBaseFee\x12\"\n" +
	"\rupdated_at_ms\x18\t \x01(\x03R\vupdatedAtMs\x12$\n" +
	"\x0ecatalog_age_ms\x18\n" +
	" \x01(\x03R\fcatalogAgeMs\x12 \n" +
	"\ttick_size\x18\v \x01(\x01H\x00R\btickSize\x88\x01\x01B\f\n" +
	"\n" +
	"_tick_size\"\x9d\x01\n" +
	"\x11CompactTradeToken\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\tR\aoutcome\x12#\n" +
	"\routcome_price\x18\x03 \x01(\x01R\foutcomePrice\x12 \n" +
	"\tuma_price\x18\x04 \x01(\x01H\x00R\bumaPrice\x88\x01\x01B\f\n" +
	"\n" +
	"_uma_priceB5Z3github.com/polymas/poly_uma/internal/wire/v5;wirev5b\x06proto3"

var (
	file_api_proto_compact_trade_v5_proto_rawDescOnce sync.Once
	file_api_proto_compact_trade_v5_proto_rawDescData []byte
)

func file_api_proto_compact_trade_v5_proto_rawDescGZIP() []byte {
	file_api_proto_compact_trade_v5_proto_rawDescOnce.Do(func() {
		file_api_proto_compact_trade_v5_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_compact_trade_v5_proto_rawDesc), len(file_api_proto_compact_trade_v5_proto_rawDesc)))
	})
	return file_api_proto_compact_trade_v5_proto_rawDescData
}

var file_api_proto_compact_trade_v5_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_compact_trade_v5_proto_goTypes = []any{
	(*CompactTradeBatch)(nil),  // 0: polyuma.wire.v5.CompactTradeBatch
	(*CompactTradeEvent)(nil),  // 1: polyuma.wire.v5.CompactTradeEvent
	(*CompactTradeMarket)(nil), // 2: polyuma.wire.v5.CompactTradeMarket
	(*CompactTradeToken)(nil),  // 3: polyuma.wire.v5.CompactTradeToken
}
var file_api_proto_compact_trade_v5_proto_depIdxs = []int32{
	1, // 0: polyuma.wire.v5.CompactTradeBatch.events:type_name -> polyuma.wire.v5.CompactTradeEvent
	2, // 1: polyuma.wire.v5.CompactTradeEvent.market:type_name -> polyuma.wire.v5.CompactTradeMarket
	3, // 2: polyuma.wire.v5.CompactTradeEvent.tokens:type_name -> polyuma.wire.v5.CompactTradeToken
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_compact_trade_v5_proto_init() }
func file_api_proto_compact_trade_v5_proto_init() {
	if File_api_proto_compact_trade_v5_proto != nil {
		return
	}
	file_api_proto_compact_trade_v5_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_compact_trade_v5_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_compact_trade_v5_proto_rawDesc), len(file_api_proto_compact_trade_v5_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_compact_trade_v5_proto_goTypes,
		DependencyIndexes: file_api_proto_compact_trade_v5_proto_depIdxs,
		MessageInfos:      file_api_proto_compact_trade_v5_proto_msgTypes,
	}.Build()
	File_api_proto_compact_trade_v5_proto = out.File
	file_api_proto_compact_trade_v5_proto_goTypes = nil
	file_api_proto_compact_trade_v5_proto_depIdxs = nil
}
